"""add_node_embedding_table

Revision ID: 0e7ab7b15f5e
Revises: 57055332f100
Create Date: 2026-01-31 18:45:38.174008

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = "0e7ab7b15f5e"
down_revision: Union[str, Sequence[str], None] = "57055332f100"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_embedding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("node_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "node_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_node_embedding_analysis_id", "node_embedding", ["analysis_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_node_embedding_analysis_id", table_name="node_embedding")
    op.drop_table("node_embedding")
    # ### end Alembic commands ###
