"""Initial schema with analysisresult table

Revision ID: aedd18522d9b
Revises: 
Create Date: 2026-01-30 15:39:19.240526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aedd18522d9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysisresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('graph_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysisresult_url_hash'), 'analysisresult', ['url_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysisresult_url_hash'), table_name='analysisresult')
    op.drop_table('analysisresult')
    # ### end Alembic commands ###
